package com.mycompany.lojainformatica;

import com.mycompany.lojainformatica.dao.ComputadorDAO;
import com.mycompany.lojainformatica.models.Computador;
import com.mysql.cj.x.protobuf.MysqlxCrud.Insert;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

public class TelaPrincipal extends javax.swing.JFrame {

    Computador objALterar = null;

    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        TabCadastar = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BtnCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextHD = new javax.swing.JTextField();
        TextProcessador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TextPesquisa = new javax.swing.JTextField();
        BtnPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblProdutos = new javax.swing.JTable();
        BtnAlterar = new javax.swing.JButton();
        BtnAdicionar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnCadastrar.setText("Cadastrar");
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AMD");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HD");

        TextHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextHDActionPerformed(evt);
            }
        });

        TextProcessador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextProcessadorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Processador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 249,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextProcessador, javax.swing.GroupLayout.PREFERRED_SIZE, 251,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                                .addComponent(TextHD)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(253, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextProcessador, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextHD, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCadastrar)
                                .addContainerGap(158, Short.MAX_VALUE)));

        TabCadastar.addTab("Cadastrar", jPanel1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Processador:");

        BtnPesquisa.setText("Pesquisar");
        BtnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisaActionPerformed(evt);
            }
        });

        TblProdutos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "ID", "Marca", "HD", "Processador"
                }));
        jScrollPane1.setViewportView(TblProdutos);

        BtnAlterar.setText("Alterar");
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });

        BtnAdicionar.setText("Adicionar");

        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 514,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(BtnPesquisa)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(BtnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnAdicionar, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnExcluir, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(TextPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BtnPesquisa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(BtnAlterar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BtnAdicionar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BtnExcluir)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        TabCadastar.addTab("Consultar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TabCadastar, javax.swing.GroupLayout.PREFERRED_SIZE, 739, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TabCadastar)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnExcluirActionPerformed
        int linhaSelecionada = TblProdutos.getSelectedRow();

        DefaultTableModel modeloTabela = (DefaultTableModel) TblProdutos.getModel();
        int idExcluir = Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada, 0).toString());
        boolean retorno = ComputadorDAO.Excluir(idExcluir);
        if (retorno) {
            JOptionPane.showMessageDialog(rootPane, "Excluido com sucesso");
            AtualizarTabela();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro ao excluir");
        }
    }// GEN-LAST:event_BtnExcluirActionPerformed

    public void AtualizarTabela() {
        ArrayList<Computador> lista = ComputadorDAO.listar();

        DefaultTableModel modelotabela = (DefaultTableModel) TblProdutos.getModel();

        modelotabela.setRowCount(0);

        for (Computador item : lista) {
            modelotabela.addRow(new String[] {
                    String.valueOf(item.getId()),
                    item.getMarca(),
                    item.getHd(),
                    item.getProcessador()
            });
        }
    }

    private void TextProcessadorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TextProcessadorActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TextProcessadorActionPerformed

    private void TextHDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TextHDActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TextHDActionPerformed

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnCadastrarActionPerformed

        if (objALterar != null) {
            // alteração

            String hd = TextHD.getText();
            String processador = TextProcessador.getText();

            objALterar.setHd(hd);
            objALterar.setProcessador(processador);

            // chamar banco
            boolean retornoAlteração = ComputadorDAO.Alterar(objALterar);

            if (retornoAlteração) {
                JOptionPane.showMessageDialog(rootPane, "Sucesso ao Alterar");

                // limpar campos

                objALterar = null;
                TextProcessador.setText("");
                TextHD.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao Alterar");
            }

        } else {
            // inclusão
            String hd = TextHD.getText();
            String processador = TextProcessador.getText();

            Computador objCadastrar = new Computador(hd, processador);
            boolean retornoBanco = ComputadorDAO.salvar(objCadastrar);

            if (retornoBanco) {
                JOptionPane.showMessageDialog(rootPane, "Cadastrado com Sucesso!");
                TextProcessador.setText("");
                TextHD.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Falha ao cadastrar");
            }

        }
    }// GEN-LAST:event_BtnCadastrarActionPerformed

    private void BtnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnPesquisaActionPerformed
        ArrayList<Computador> lista = ComputadorDAO.listar();

        DefaultTableModel modelotabela = (DefaultTableModel) TblProdutos.getModel();

        modelotabela.setRowCount(0);

        for (Computador item : lista) {
            modelotabela.addRow(new String[] {
                    String.valueOf(item.getId()),
                    item.getMarca(),
                    item.getHd(),
                    item.getProcessador()
            });
        }
    }// GEN-LAST:event_BtnPesquisaActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnAlterarActionPerformed
        DefaultTableModel modeloProduto = (DefaultTableModel) TblProdutos.getModel();

        int linhaSelecionada = TblProdutos.getSelectedRow();

        if (linhaSelecionada >= 0) {
            int id = Integer.parseInt(modeloProduto.getValueAt(linhaSelecionada, 0).toString());
            String hd = modeloProduto.getValueAt(linhaSelecionada, 2).toString();
            String processador = modeloProduto.getValueAt(linhaSelecionada, 3).toString();

            objALterar = new Computador(id, hd, processador);

            // //Redirecionar tela de cadastro
            TabCadastar.setSelectedIndex(0);
            TextProcessador.setText(String.valueOf(objALterar.getProcessador()));
            TextHD.setText(String.valueOf(objALterar.getHd()));

        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Selecione um linha da tabela ");
        }
    }// GEN-LAST:event_BtnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdicionar;
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnPesquisa;
    private javax.swing.JTabbedPane TabCadastar;
    private javax.swing.JTable TblProdutos;
    private javax.swing.JTextField TextHD;
    private javax.swing.JTextField TextPesquisa;
    private javax.swing.JTextField TextProcessador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
